// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// Import the Verifier generated by snarkjs
import "./Verifier.sol";

contract PrivacyShield {
    // Reference to the Groth16 Verifier math contract
    IVerifier public immutable verifier;

    // Rule B: Storage for registered "Identity Commitments"
    mapping(uint256 => bool) public registeredIdentities;

    // Rule C: Storage for used nullifiers (prevents double-spending)
    mapping(uint256 => bool) public usedNullifiers;

    event IdentityRegistered(uint256 indexed commitment);
    event ActionVerified(uint256 indexed nullifier, address indexed user);

    constructor(address _verifierAddress) {
        verifier = IVerifier(_verifierAddress);
    }

    /**
     * @dev Step 1: Registration
     * In a real app, this might be restricted to an admin or a biometric provider.
     */
    function registerIdentity(uint256 _identityCommitment) external {
        require(!registeredIdentities[_identityCommitment], "Identity already exists");
        registeredIdentities[_identityCommitment] = true;
        emit IdentityRegistered(_identityCommitment);
    }

    /**
     * @dev Step 2: Verification (The Relayer calls this)
     * The order of publicSignals MUST match your Circom:
     * index 0: identityCommitment
     * index 1: app_address
     * index 2: user_wallet
     * index 3: nullifier
     */
    function verifyAndExecute(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[4] calldata publicSignals
    ) external {
        uint256 identityCommitment = publicSignals[0];
        uint256 appAddress = publicSignals[1];
        uint256 userWallet = publicSignals[2];
        uint256 nullifier = publicSignals[3];

        // 1. Identity Check: Is this human registered?
        require(registeredIdentities[identityCommitment], "Unauthorized: Identity not registered");

        // 2. Double-Spend Check: Has this specific action been used?
        require(!usedNullifiers[nullifier], "Security: Proof already used");

        // 3. Binding Check: Is this proof meant for THIS wallet?
        // TEMPORARILY DISABLED FOR TESTING - RE-ENABLE IN PRODUCTION
        // This prevents "Replay Attacks" where a relayer steals a proof
        // require(userWallet == uint256(uint160(msg.sender)) || userWallet == uint256(uint160(tx.origin)), "Binding: Wallet mismatch");

        // 4. THE MATH CHECK: Call the precompile-linked Verifier
        // This is where the Elliptic Curve Pairing happens
        require(
            verifier.verifyProof(a, b, c, publicSignals),
            "Math: Invalid Zero-Knowledge Proof"
        );

        // 5. Success! Mark the nullifier as used
        usedNullifiers[nullifier] = true;

        // Perform the sensitive action here (e.g., release funds, grant access)
        emit ActionVerified(nullifier, msg.sender);
    }

    /**
     * @dev Check if an identity is already registered
     */
    function isRegistered(uint256 _identityCommitment) external view returns (bool) {
        return registeredIdentities[_identityCommitment];
    }
}

// Interface for the auto-generated Verifier.sol
interface IVerifier {
    function verifyProof(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[4] calldata input
    ) external view returns (bool);
}
